### PR TITLE
Rewrite parser code, fix number parsing bugs, improve tests, adapt to v0.7

### PR DESCRIPTION
**Pull request by ScottPJones**

### CODE REVIEW

**Comment by stevengj** [comment]
Do you have some benchmarks of the parsing performance compared to the master branch?

**Comment by ScottPJones** [comment]
Yes, but I have to fix this up first, I messed up squashing some of the changes (there were about 13 commits!)

**Comment by ScottPJones** [comment]
I did post using the benchmarks already though on the JSON2.jl comments, as I'd like to see how it (and Sam's LazyJSON) compare.  Jacob had some good ideas with the named tuples and parsing floats I want to look into.

**Comment by ScottPJones** [comment]
Results from old master (before #236):
```julia
Test: canada
  85.769 ms (777646 allocations: 33.44 MiB)
Test: citm_catalog
  12.838 ms (195138 allocations: 12.69 MiB)
Test: twitter
  4.241 ms (50701 allocations: 3.48 MiB)
Test: citylots
  7.780 s (58396623 allocations: 2.71 GiB)
```
Results from master (after #236):
```julia
Test: canada
  77.823 ms (777633 allocations: 33.44 MiB)
Test: citm_catalog
  10.896 ms (168537 allocations: 11.07 MiB)
Test: twitter
  3.793 ms (33849 allocations: 2.48 MiB)
Test: citylots
  6.794 s (53286967 allocations: 2.40 GiB)
```
Results with this change:
```julia
Test: canada
  58.763 ms (670280 allocations: 24.26 MiB)
Test: citm_catalog
  11.227 ms (227678 allocations: 11.62 MiB)
Test: twitter
  4.099 ms (69993 allocations: 3.17 MiB)
Test: citylots
  6.305 s (60191447 allocations: 2.21 GiB)
```
Results with #243:
```julia
Test: canada
  54.585 ms (670266 allocations: 24.26 MiB)
Test: citm_catalog
  8.604 ms (213296 allocations: 11.18 MiB)
Test: twitter
  3.660 ms (68353 allocations: 3.12 MiB)
Test: citylots
  5.863 s (60191476 allocations: 2.21 GiB)
```

**Comment by TotalVerb** [comment]
This pull request is a little hard to review because it renames a lot of files, and GitHub can't identify the changes. Could you move the file renames to a different PR, if possible?

**Comment by kmsquire** [comment]
@ScottPJones, thanks for your contribution here.  There have been a lot of changes since this was written, so it would probably have to be redone from scratch, if you're still interested.  

In the future, to ensure faster review, it would be better to break large pull requests like this in to a sequence of smaller, self-contained pull requests.  Cheers!

**Pull request closed without merging**
