### PR TITLE
Make it possible to specify float type as well

### PR DESCRIPTION
**Pull request by Keno**
I have an application dealing with decimal money amounts sent via JSON,
I want to parse these as a FixedPointDecimal (
https://github.com/JuliaMath/FixedPointDecimals.jl) to make sure floating
point doesn't mess up my amounts. This code is sufficient to convience
JSON.jl to parse numbers as FixedPointDecimals.

### CODE REVIEW

**Comment by kmsquire** [comment]
Looks good!  Can you add some tests?

**Comment by ScottPJones** [comment]
It would be good to have this tested with https://github.com/stevengj/DecFP.jl as well.

**Comment by kmsquire** [comment]
@Keno are you still interested in this pull request?

**Comment by Keno** [comment]
abstractly yes, but I'm unlikely to have the time to get back to it in the near future, so feel free to close.

**Pull request closed without merging**
