### PR TITLE
Parse floats using Parsers.jl (fixes #284)

### LINKED ISSUE #284: Switch number parsing to Parsers.jl
Recent profiling suggests that a lot of parse time is spent parsing numbers.  Right now, this is done via a `ccall` to `jl_try_substrtod`. 

Parsers.jl has parsers for various number types written in pure Julia. It would be good to test if these might be faster.

### PR DESCRIPTION
**Pull request by kmsquire**
On my machine, this gives a good speedup on the (minimal) benchmarks that we have (and we now are faster than Python!):

Before:
```
$ julia1.1 bench.jl parse -f
 [BenchF] canada 0.053259659 seconds
 [BenchF] citm_catalog 0.010465748 seconds
 [BenchF] citylots 3.622005479 seconds
 [BenchF] twitter 0.004414869 seconds
 [BenchF] Total (G.M.) 0.0546397740591351 seconds
```

After:
```
$ julia1.1 bench/bench.jl parse -f
 [BenchF] canada 0.034515661 seconds
 [BenchF] citm_catalog 0.009896403 seconds
 [BenchF] citylots 3.371572698 seconds
 [BenchF] twitter 0.003937035 seconds
 [BenchF] Total (G.M.) 0.04614491419775058 seconds
```

Python:
```
$ python3 bench.py
canada 0.040348 seconds
citm_catalog 0.011868 seconds
citylots 3.509695 seconds
twitter 0.005907 seconds
Total (G.M): 0.056133
```

Cc: @quinnj @TotalVerb

### CODE REVIEW

**Comment by kmsquire** [comment]
I'll pull the transition to `Project.toml` out into its own pull request (except for the extra dependencies pulled in by `Parsers.jl`).

**Comment by kmsquire** [comment]
One Appveyor build failed because of a DNS lookup (unrelated).  I hesitate to close and open just to run everything again, especially if I should make any changes, and I don't have permissions to restart just that build.

**Comment by TotalVerb** [comment]
I'm not sure I have permission to restart appveyor either. I'm fine with the spurious failure since it's on 0.7 anyway.

**Comment by tlnagy** [comment]
Unfortunately, it looks like this PR was included in a JSON.jl release that still has support for 0.7 listed in its compat section in the `Project.toml` so it broke our tests over on Gadfly (actually in Compose.jl: https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/583375273). 

Here: https://github.com/JuliaRegistries/General/pull/2060/files#diff-68074356855d5796422b09f38b90317fR41

I'll open an issue over there to get this fixed retroactively.

**Pull request merged**
