### PR TITLE
Add support for missing

### PR DESCRIPTION
**Pull request by YongHee-Kim**
https://github.com/JuliaIO/JSON.jl/issues/256

### CODE REVIEW

**Comment by KristofferC** [comment]
Isn't it a bit odd for two quite different Julia objects to serialize to the same representation?

**Comment by YongHee-Kim** [comment]
Yes, I'm not knowledgeable enough to discuss this matter. 

Just thought this in user's perspective. `.json` is for storing data and we are encouraged to use Union{T, Missing} for handling data. So whenever someone wants to store something with missing, they will encounter errors. 
So if two different Julia objects to serialize to the same representation is problematic, maybe serialize `missing` to `null` and nothing to `"nothing"` would be a better solution?

**Comment by quinnj** [comment]
I support this; JSON is limited in that it has a notion of `null`, but no way to distinguish the use in Julia of `nothing` as a software engineer's null or `missing` as missing data. I see JSON structures all the time that conflate the two. I think this is the most natural serialization strategy.

**Comment by TotalVerb** [comment]
I think this is very reasonable. Could also consider a `lower(::Missing) = null` method, which might be cleaner.

**Comment by TotalVerb** [comment]
As there are 4 votes in support, I think we should merge this.

**Comment by YongHee-Kim** [comment]
Isn't this breaking change for 0.6? 
should add `using Missings` for 0.6

**Comment by TotalVerb** [comment]
I haven't tagged this yet. Since tests aren't being run on 0.6, we should
just drop support.

**Comment by TotalVerb** [comment]
Actually, 0.6 is already not present in REQUIRE, so there is no action required (unless we want to backport a fix to 0.6?).

**Pull request merged**
